// 列表页配置。字段与格式都声明在这里，页面组件不出现任何格式化逻辑。
// method 多数后台列表是 POST；products/List 与 inventory/List 后端写的是 GET。
// response 形状不统一（有的分页信封、有的裸数组），由 ListView 兼容。

// 审核动作。商户与商品的「审核列表」和「全部列表」共用同一组按钮，
// 所以抽成常量——写两份的话，改了拒绝原因必填的提示就会只改到一半。
// 两个后端的审核状态码**不一样**：商户 20 通过 / 90 拒绝（MerchantAuditStatuses），
// 商品 20 通过 / 30 驳回（AuditStatuses）。写成同一套会直接调错参数。
const MERCHANT_AUDIT_ACTIONS = [
  {
    label: '通过',
    endpoint: '/gateway/merchants/Audit',
    okText: '已通过审核',
    permission: 'merchant:audit',
    // 放在 action 上而不是 confirm 里：确认框的危险色读的是 action.danger
    // （`action.danger !== false`）。写在 confirm 里会被忽略，
    // 于是「通过」这个正向动作的确认按钮会是红色的 —— 看着像要出事。
    danger: false,
    build: (r: any) => ({ merchantId: r.id, auditStatus: 20, auditRemark: '' }),
    showWhen: (r: any) => r.auditStatus === 10,
    confirm: {
      title: '通过商户审核',
      message: '通过后该商户会出现在小程序里，用户可以浏览并下单。',
      subject: (r: any) => `${r.merchantName}（${r.merchantNo}）`,
      okText: '通过',
    },
  },
  {
    label: '拒绝',
    endpoint: '/gateway/merchants/Audit',
    danger: true,
    okText: '已拒绝',
    permission: 'merchant:audit',
    build: (r: any, reason: string) => ({ merchantId: r.id, auditStatus: 90, auditRemark: reason }),
    showWhen: (r: any) => r.auditStatus === 10,
    confirm: {
      title: '拒绝商户审核',
      message: '拒绝会连带下架该商户的全部商品。商户需要修改资料后重新提交。',
      subject: (r: any) => `${r.merchantName}（${r.merchantNo}）`,
      okText: '拒绝',
      danger: true,
      withReason: true,
      reasonLabel: '拒绝原因',
      reasonPlaceholder: '商户要知道为什么被拒，否则只能反复提交碰运气',
    },
  },
];

const PRODUCT_AUDIT_ACTIONS = [
  {
    label: '通过',
    endpoint: '/gateway/products/Audit',
    okText: '已通过审核',
    permission: 'product:audit',
    danger: false,
    build: (r: any) => ({ productId: r.id, auditStatus: 20, reason: '' }),
    showWhen: (r: any) => r.auditStatus === 10,
    confirm: {
      title: '通过商品审核',
      message: '通过后商品可以上架销售。',
      subject: (r: any) => r.spuName,
      okText: '通过',
    },
  },
  {
    label: '驳回',
    endpoint: '/gateway/products/Audit',
    danger: true,
    okText: '已驳回',
    permission: 'product:audit',
    build: (r: any, reason: string) => ({ productId: r.id, auditStatus: 30, reason }),
    showWhen: (r: any) => r.auditStatus === 10,
    confirm: {
      title: '驳回商品审核',
      message: '驳回后商户需要修改资料并重新提交审核。',
      subject: (r: any) => r.spuName,
      okText: '驳回',
      danger: true,
      withReason: true,
      reasonLabel: '驳回原因',
      reasonPlaceholder: '写清楚哪里不符合要求，商户才知道要改什么',
    },
  },
];

export const LISTS = {
  products: {
    title: '商品列表',
    desc: 'SPU 与价格区间，审核与上下架状态',
    createRoute: '/products/create',
    createLabel: '新建商品',
    createPermission: 'product:create',
    rowRoute: (r: any) => `/products/edit/${r.id}`,
    editRoute: (r: any) => `/products/edit/${r.id}`,
    editPermission: 'product:update',
    endpoint: '/gateway/products/List',
    method: 'GET',
    tabs: [
      { label: '全部', value: 0 },
      { label: '待审核', value: 10 },
      { label: '已通过', value: 20 },
      { label: '已拒绝', value: 30 },
    ],
    byStatus: true,
    search: true,
    searchPlaceholder: '商品名 / 编码',
    statusField: 'auditStatus',
    columns: [
      { field: 'spuName', label: '商品', width: 220 },
      { field: 'brandName', label: '品牌', width: 110, format: 'text' },
      { field: 'categoryName', label: '分类', width: 130, format: 'text' },
      { field: 'minPrice', label: '最低价', width: 100, num: true, format: 'amount' },
      { field: 'maxPrice', label: '最高价', width: 100, num: true, format: 'amount' },
      { field: 'auditStatus', label: '审核', width: 100, dict: 'audit' },
      { field: 'status', label: '上下架', width: 100, dict: 'shelf' },
      { field: 'sales', label: '销量', width: 90, num: true, format: 'count' },
    ],
    actions: [
      ...PRODUCT_AUDIT_ACTIONS,
      {
        label: '上架',
        endpoint: '/gateway/products/ChangeListing',
        okText: '商品已上架',
        permission: 'product:update',
        showWhen: (r: any) => Number(r.status) === 2 && Number(r.auditStatus) === 20,
        build: (r: any) => ({ productId: r.id, status: 1 }),
        confirm: {
          title: '上架商品',
          message: '上架后商品会进入小程序商品列表与搜索。',
          subject: (r: any) => r.spuName,
          okText: '上架',
        },
      },
      {
        label: '下架',
        endpoint: '/gateway/products/ChangeListing',
        danger: true,
        okText: '商品已下架',
        permission: 'product:update',
        showWhen: (r: any) => Number(r.status) === 1,
        build: (r: any) => ({ productId: r.id, status: 2 }),
        confirm: {
          title: '下架商品',
          message: '下架后不删除历史订单，商品从小程序列表与搜索中移除。',
          subject: (r: any) => r.spuName,
          okText: '下架',
          danger: true,
        },
      },
      {
        label: '重新提交审核',
        endpoint: '/gateway/products/SubmitAudit',
        okText: '已提交审核',
        permission: 'product:update',
        showWhen: (r: any) => Number(r.auditStatus) === 30,
        build: (r: any) => ({ productId: r.id }),
      },
    ],
    actionsWidth: 260,
  },

  // 商品审核页 = 同一张表，默认落在「待审核」。
  productAudits: {
    title: '商品审核',
    desc: '审核通过后商品才能上架销售',
    endpoint: '/gateway/products/List',
    method: 'GET',
    tabs: [
      { label: '待审核', value: 10 },
      { label: '已通过', value: 20 },
      { label: '已驳回', value: 30 },
      { label: '全部', value: 0 },
    ],
    byStatus: true,
    defaultStatus: 10,
    statusField: 'auditStatus',
    search: true,
    searchPlaceholder: '商品名 / 编码',
    columns: [
      { field: 'spuName', label: '商品', width: 220 },
      { field: 'brandName', label: '品牌', width: 110, format: 'text' },
      { field: 'categoryName', label: '分类', width: 130, format: 'text' },
      { field: 'minPrice', label: '最低价', width: 100, num: true, format: 'amount' },
      { field: 'maxPrice', label: '最高价', width: 100, num: true, format: 'amount' },
      { field: 'auditStatus', label: '审核', width: 100, dict: 'audit' },
      { field: 'status', label: '上下架', width: 100, dict: 'shelf' },
    ],
    actions: PRODUCT_AUDIT_ACTIONS,
    actionsWidth: 150,
  },

  inventory: {
    title: '库存管理',
    desc: '可用 / 锁定 / 已扣，以及预警阈值',
    endpoint: '/gateway/inventory/List',
    method: 'GET',
    search: true,
    searchPlaceholder: '商品名 / 规格',
    columns: [
      { field: 'productName', label: '商品', width: 220 },
      { field: 'skuSpecText', label: '规格', width: 120, format: 'text' },
      { field: 'available', label: '可用', width: 90, num: true, format: 'count' },
      { field: 'locked', label: '锁定', width: 90, num: true, format: 'count' },
      { field: 'deducted', label: '已扣', width: 90, num: true, format: 'count' },
      { field: 'warnThreshold', label: '预警阈值', width: 110, num: true, format: 'count' },
      {
        field: 'isLowStock',
        label: '预警',
        width: 90,
        dict: 'lowStock',
      },
      { field: 'updatedAt', label: '更新时间', width: 150, format: 'time' },
    ],
    actions: [
      {
        label: '调整库存',
        endpoint: '/gateway/inventory/Adjust',
        okText: '库存已调整',
        permission: 'inventory:update',
        build: (r: any, value: any) => ({
          skuId: r.skuId,
          availableAdjust: Number(value.availableAdjust),
          remark: value.remark,
          warnThreshold: Number(r.warnThreshold || 0),
        }),
        confirm: {
          title: '调整可用库存',
          message: '提交的是调整量，不是最终值。例如当前可用 10、填 5 会变成 15；填 -3 会变成 7。',
          subject: (r: any) => `${r.productName} / ${r.skuSpecText || '默认规格'}｜当前可用 ${r.available}`,
          okText: '确认调整',
          fields: [
            {
              name: 'availableAdjust',
              label: '调整量',
              type: 'number',
              required: true,
              placeholder: '可正可负，例如 5 或 -3',
            },
            {
              name: 'remark',
              label: '调整原因',
              type: 'textarea',
              rows: 3,
              required: true,
              minLength: 2,
              maxlength: 200,
              placeholder: '会写入库存流水，至少 2 个字符',
            },
          ],
        },
      },
    ],
    actionsWidth: 130,
  },

  customers: {
    title: '客户列表',
    desc: '按登录名 / 昵称 / 手机号搜索，可停用',
    // 客户详情是独立页面（从列表点行进去），不是弹窗：详情要放订单、
    // 地址、积分这些一屏放不下的东西，弹窗里没法读。
    rowRoute: (r: any) => `/customers/detail/${r.customerId ?? r.id}`,
    endpoint: '/gateway/admin/customers/List',
    method: 'POST',
    byStatus: true,
    tabs: [
      { label: '全部', value: 0 },
      { label: '正常', value: 1 },
      { label: '已停用', value: 2 },
    ],
    search: true,
    searchPlaceholder: '登录名 / 昵称 / 手机号',
    columns: [
      { field: 'customerName', label: '登录名', width: 150 },
      { field: 'nickName', label: '昵称', width: 130, format: 'text' },
      // 后台要给客服完整手机号找人，脱敏了就等于没法用
      { field: 'phone', label: '手机号', width: 140, format: 'text' },
      { field: 'genderName', label: '性别', width: 80, format: 'text' },
      { field: 'status', label: '状态', width: 100, dict: 'customer' },
      { field: 'lastLoginAt', label: '最后登录', width: 150, format: 'time' },
      { field: 'createdAt', label: '注册时间', width: 150, format: 'time' },
    ],
    actions: [
      {
        label: '停用',
        endpoint: '/gateway/admin/customers/ChangeStatus',
        danger: true,
        okText: '已停用',
        permission: 'customer:status',
        showWhen: (r: any) => Number(r.status) === 1,
        build: (r: any) => ({ customerId: r.customerId, status: 2 }),
      },
      {
        label: '启用',
        endpoint: '/gateway/admin/customers/ChangeStatus',
        okText: '已启用',
        permission: 'customer:status',
        showWhen: (r: any) => Number(r.status) === 2,
        build: (r: any) => ({ customerId: r.customerId, status: 1 }),
      },
    ],
    actionsWidth: 180,
  },

  brands: {
    title: '品牌管理',
    desc: '商品品牌，删除前需先解绑商品',
    createRoute: '/brands/create',
    createLabel: '新建品牌',
    rowRoute: (r: any) => `/brands/edit/${r.id}`,
    editRoute: (r: any) => `/brands/edit/${r.id}`,
    actions: [
      {
        label: '删除',
        endpoint: '/gateway/brands/Delete',
        danger: true,
        okText: '已删除',
        build: (r: any) => ({ brandId: r.id }),
        confirm: {
          title: '删除品牌',
          message: '品牌下有商品时会拒绝删除，只能改为停用。',
          subject: (r: any) => r.brandName,
          okText: '删除',
        },
      },
    ],
    actionsWidth: 150,
    endpoint: '/gateway/brands/List',
    method: 'GET',
    search: true,
    searchPlaceholder: '品牌名 / 编码',
    columns: [
      { field: 'brandName', label: '品牌名', width: 160 },
      { field: 'brandCode', label: '编码', width: 140, format: 'text' },
      { field: 'logo', label: 'Logo', width: 100, format: 'text' },
      { field: 'sort', label: '排序', width: 90, num: true, format: 'count' },
      { field: 'createdAt', label: '创建时间', width: 160, format: 'time' },
    ],
  },

  evaluates: {
    title: '评价管理',
    desc: 'SPU 级评价，可隐藏与回复',
    endpoint: '/gateway/evaluates/admin/List',
    method: 'POST',
    search: true,
    searchPlaceholder: '商品名 / 客户 / 内容',
    columns: [
      { field: 'spuName', label: '商品', width: 180 },
      { field: 'starScore', label: '评分', width: 90, num: true, format: 'score' },
      { field: 'content', label: '评价内容', width: 240, format: 'text' },
      { field: 'customerName', label: '客户', width: 120, format: 'text' },
      {
        field: 'isAnonymous',
        label: '匿名',
        width: 90,
        dict: 'anonymous',
      },
      {
        field: 'isHidden',
        label: '展示',
        width: 90,
        dict: 'hidden',
      },
      { field: 'createdAt', label: '评价时间', width: 150, format: 'time' },
    ],
    actions: [
      {
        label: '回复',
        endpoint: '/gateway/evaluates/admin/Reply',
        okText: '已回复',
        permission: 'evaluate:reply',
        build: (r: any, text: string) => ({
          evaluateId: r.evaluateId,
          appendId: 0,
          replyContent: text,
          replyType: 1,
        }),
        // 同一主体（商户 / 平台）各只能回 1 次，所以最多 2 条回复。
        // 满 2 条就把按钮藏掉 —— 给一个必然失败的按钮没有意义。
        showWhen: (r: any) => (r.replies || []).length < 2,
        confirm: {
          title: '回复评价',
          message: '回复对所有能看到这条评价的客户可见。',
          subject: (r: any) => r.content,
          okText: '回复',
          withReason: true,
          reasonLabel: '回复内容',
          reasonPlaceholder: '2-500 字。同一主体（商户 / 平台）各只能回 1 次',
        },
      },
      {
        label: '隐藏',
        endpoint: '/gateway/evaluates/admin/Hide',
        danger: true,
        okText: '已隐藏',
        permission: 'evaluate:manage',
        build: (r: any, text: string) => ({
          evaluateId: r.evaluateId,
          isHidden: true,
          hiddenReason: text,
        }),
        showWhen: (r: any) => r.isHidden !== true,
        confirm: {
          title: '隐藏评价',
          message: '隐藏只是不展示，数据仍在；客户能在「我的评价」里看到「已被隐藏」。',
          subject: (r: any) => r.content,
          okText: '隐藏',
          danger: true,
          withReason: true,
          reasonLabel: '隐藏原因',
          reasonPlaceholder: '2-200 字。会记入后台审计，出了问题要能追溯',
        },
      },
      {
        label: '恢复',
        endpoint: '/gateway/evaluates/admin/Hide',
        okText: '已恢复显示',
        permission: 'evaluate:manage',
        build: (r: any) => ({ evaluateId: r.evaluateId, isHidden: false, hiddenReason: '' }),
        showWhen: (r: any) => r.isHidden === true,
        confirm: {
          title: '恢复显示',
          message: '恢复后这条评价会重新参与商品均分计算。',
          subject: (r: any) => r.content,
          okText: '恢复',
        },
      },
    ],
    actionsWidth: 170,
  },

  operationLogs: {
    title: '操作日志',
    desc: '后台写操作留痕',
    endpoint: '/gateway/logs/Operation/List',
    method: 'POST',
    columns: [
      { field: 'occurredAt', label: '时间', width: 155, format: 'time' },
      { field: 'service', label: '服务', width: 150, format: 'text' },
      { field: 'operatorName', label: '操作人', width: 110, format: 'text' },
      { field: 'method', label: '方法', width: 80, format: 'text' },
      { field: 'path', label: '路径', width: 240, format: 'text' },
      { field: 'statusCode', label: '响应码', width: 90, num: true, format: 'count' },
      { field: 'elapsedMs', label: '耗时', width: 90, num: true, format: 'ms' },
      // 请求 Id 是编码类字段，等宽字体才能逐位比对
      { field: 'requestId', label: '请求 Id', width: 220, format: 'text', mono: true },
    ],
  },

  exceptionLogs: {
    title: '异常日志',
    desc: '未处理异常，点消息看完整堆栈',
    endpoint: '/gateway/logs/Exception/List',
    method: 'POST',
    columns: [
      { field: 'occurredAt', label: '时间', width: 155, format: 'time' },
      { field: 'service', label: '服务', width: 150, format: 'text' },
      { field: 'path', label: '路径', width: 220, format: 'text' },
      { field: 'message', label: '异常消息', width: 280, format: 'text' },
      { field: 'requestId', label: '请求 Id', width: 220, format: 'text', mono: true },
    ],
    actions: [
      {
        label: '查看堆栈',
        inspect: {
          endpoint: '/gateway/logs/Exception/Stack',
          build: (r: any) => ({ id: r.id }),
        },
        permission: 'log:read',
      },
    ],
    actionsWidth: 120,
  },

  deadLetters: {
    title: '死信与重放',
    desc: '重试耗尽的消息，可按 EventId 精确重放',
    endpoint: '/gateway/logs/DeadLetter/List',
    method: 'POST',
    columns: [
      { field: 'failedAt', label: '失败时间', width: 155, format: 'time' },
      { field: 'eventType', label: '事件', width: 130, format: 'text' },
      { field: 'queueName', label: '队列', width: 150, format: 'text' },
      { field: 'errorMessage', label: '失败原因', width: 300, format: 'text' },
      { field: 'attempts', label: '尝试', width: 80, num: true, format: 'count' },
      { field: 'replayCount', label: '已重放', width: 90, num: true, format: 'count' },
    ],
    actions: [
      {
        label: '重放',
        endpoint: '/gateway/logs/DeadLetter/Replay',
        okText: '已重放',
        permission: 'log:read',
        build: (r: any) => ({ eventId: r.eventId }),
      },
    ],
    actionsWidth: 100,
    emptyHint: '没有死信 —— 消费链路是健康的',
  },

  users: {
    title: '账号列表',
    desc: '后台账号，密码只存哈希',
    // 「新建」按钮开新页；点整行进编辑页。两者都不在侧边栏里。
    createRoute: '/users/create',
    createLabel: '新建账号',
    createPermission: 'user:create',
    rowRoute: (r: any) => `/users/edit/${r.id}`,
    editRoute: (r: any) => `/users/edit/${r.id}`,
    editPermission: 'user:update',
    endpoint: '/gateway/users/List',
    method: 'GET',
    search: true,
    searchPlaceholder: '账号 / 姓名 / 手机号',
    columns: [
      { field: 'userName', label: '账号', width: 150 },
      { field: 'nickName', label: '姓名', width: 120, format: 'text' },
      { field: 'phone', label: '手机号', width: 140, format: 'text' },
      { field: 'tenantTypeText', label: '租户类型', width: 110, format: 'text' },
      { field: 'platformName', label: '所属平台', width: 130, format: 'text' },
      { field: 'merchantName', label: '所属商户', width: 130, format: 'text' },
      { field: 'status', label: '状态', width: 90, dict: 'userStatus' },
      { field: 'lastLoginAt', label: '最后登录', width: 155, format: 'time' },
    ],
    actions: [
      {
        label: '重置密码',
        endpoint: '/gateway/users/ResetPassword',
        okText: '密码已重置',
        permission: 'user:update',
        build: (r: any, value: any) => ({ userId: r.id, newPassword: value.newPassword }),
        confirm: {
          title: '重置登录密码',
          message: '旧密码会立即失效，账号当前的登录令牌不受影响；请通过安全渠道把新密码交给本人。',
          subject: (r: any) => r.userName,
          okText: '重置密码',
          fields: [
            {
              name: 'newPassword',
              label: '新密码',
              type: 'password',
              required: true,
              minLength: 8,
              placeholder: '至少 8 位，建议字母与数字组合',
            },
          ],
        },
      },
      {
        label: '停用',
        endpoint: '/gateway/users/UpdateStatus',
        danger: true,
        okText: '账号已停用',
        permission: 'user:status',
        showWhen: (r: any) => Number(r.status) === 1,
        build: (r: any) => ({ userId: r.id, status: 2 }),
        confirm: {
          title: '停用后台账号',
          message: '停用后该账号无法再登录；已签发的令牌会在过期后失效。',
          subject: (r: any) => `${r.userName}（${r.nickName || '未填姓名'}）`,
          okText: '停用',
          danger: true,
        },
      },
      {
        label: '启用',
        endpoint: '/gateway/users/UpdateStatus',
        okText: '账号已启用',
        permission: 'user:status',
        showWhen: (r: any) => Number(r.status) === 2,
        build: (r: any) => ({ userId: r.id, status: 1 }),
        confirm: {
          title: '启用后台账号',
          message: '启用后该账号可以重新登录。',
          subject: (r: any) => r.userName,
          okText: '启用',
        },
      },
    ],
    actionsWidth: 220,
  },

  roles: {
    title: '角色列表',
    desc: '内置角色不可编辑',
    createRoute: '/roles/create',
    createLabel: '新建角色',
    createPermission: 'permission:create',
    rowRoute: (r: any) => `/roles/edit/${r.id}`,
    editRoute: (r: any) => `/roles/edit/${r.id}`,
    editPermission: 'permission:update',
    endpoint: '/gateway/roles/List',
    method: 'GET',
    columns: [
      { field: 'roleName', label: '角色名', width: 150 },
      { field: 'code', label: '编码', width: 160, format: 'text', mono: true },
      { field: 'dataScope', label: '数据范围', width: 120, format: 'text' },
      { field: 'permissionCount', label: '权限点数', width: 100, num: true, format: 'count' },
      { field: 'status', label: '状态', width: 90, dict: 'roleStatus' },
      { field: 'isBuiltin', label: '内置', width: 90, dict: 'builtin' },
      { field: 'remark', label: '备注', width: 220, format: 'text' },
    ],
    actions: [
      {
        label: '分配权限',
        route: (r: any) => `/roles/permissions/${r.id}`,
        permission: 'permission:manage',
        showWhen: (r: any) => !r.isBuiltin,
      },
      {
        label: '删除',
        endpoint: '/gateway/roles/Delete',
        danger: true,
        okText: '角色已删除',
        permission: 'permission:delete',
        showWhen: (r: any) => !r.isBuiltin,
        build: (r: any) => ({ roleId: r.id }),
        confirm: {
          title: '删除角色',
          message: '删除角色会同时清除它与权限点的绑定；仍在使用该角色的账号会失去对应权限。',
          subject: (r: any) => `${r.roleName}（${r.code}）`,
          okText: '删除',
          danger: true,
        },
      },
    ],
    actionsWidth: 210,
  },

  platforms: {
    title: '平台列表',
    desc: '小程序主体，每个平台一套配置',
    createRoute: '/platforms/create',
    createLabel: '新建平台',
    createPermission: 'platform:create',
    rowRoute: (r: any) => `/platforms/edit/${r.id}`,
    editRoute: (r: any) => `/platforms/edit/${r.id}`,
    editPermission: 'platform:update',
    endpoint: '/gateway/platforms/List',
    method: 'POST',
    search: true,
    searchPlaceholder: '平台名 / 编码',
    columns: [
      { field: 'platformName', label: '平台名', width: 150 },
      { field: 'platformCode', label: '平台编码', width: 130, format: 'text', mono: true },
      { field: 'mallName', label: '商城名', width: 140, format: 'text' },
      { field: 'contactName', label: '联系人', width: 110, format: 'text' },
      { field: 'contactPhone', label: '联系电话', width: 130, format: 'text' },
      { field: 'merchantCount', label: '商户数', width: 90, num: true, format: 'count' },
      { field: 'status', label: '状态', width: 90, dict: 'userStatus' },
      { field: 'createdAt', label: '创建时间', width: 155, format: 'time' },
    ],
    actions: [
      {
        label: '小程序配置',
        route: (r: any) => `/platforms/app-config/${r.id}`,
        permission: 'platform:update',
      },
      {
        label: '删除',
        endpoint: '/gateway/platforms/Delete',
        danger: true,
        okText: '平台已删除',
        permission: 'platform:update',
        showWhen: (r: any) => Number(r.merchantCount || 0) === 0,
        build: (r: any) => ({ platformId: r.id }),
        confirm: {
          title: '删除平台',
          message: '平台下没有任何商户时才允许删除。删除后平台配置不可恢复。',
          subject: (r: any) => `${r.platformName}（${r.platformCode}）`,
          okText: '删除平台',
          danger: true,
        },
      },
    ],
    actionsWidth: 210,
  },

  merchants: {
    title: '商户列表',
    desc: '审核通过后小程序才可见',
    createRoute: '/merchants/create',
    createLabel: '新建商户',
    createPermission: 'merchant:create',
    rowRoute: (r: any) => `/merchants/edit/${r.id}`,
    editRoute: (r: any) => `/merchants/edit/${r.id}`,
    editPermission: 'merchant:update',
    endpoint: '/gateway/merchants/List',
    method: 'POST',
    tabs: [
      { label: '全部', value: 0 },
      { label: '待审核', value: 10 },
      { label: '已通过', value: 20 },
      { label: '已拒绝', value: 30 },
    ],
    byStatus: true,
    search: true,
    searchPlaceholder: '商户名 / 编号 / 联系人',
    statusField: 'auditStatus',
    columns: [
      { field: 'merchantName', label: '商户名', width: 150 },
      { field: 'merchantNo', label: '商户编号', width: 140, format: 'text', mono: true },
      { field: 'platformName', label: '所属平台', width: 130, format: 'text' },
      { field: 'contactName', label: '联系人', width: 110, format: 'text' },
      { field: 'contactPhone', label: '联系电话', width: 130, format: 'text' },
      { field: 'auditStatus', label: '审核', width: 100, dict: 'audit' },
      // 启用/停用是与审核**独立**的一列：审核通过的商户也可能被停用，
      // 看不到这一列的话运营分不清「没通过审核」和「通过了但被停用」。
      { field: 'status', label: '启用', width: 90, dict: 'enable' },
      { field: 'rating', label: '评分', width: 90, num: true, format: 'score' },
      { field: 'createdAt', label: '入驻时间', width: 155, format: 'time' },
    ],
    actions: [
      ...MERCHANT_AUDIT_ACTIONS,
      {
        label: '删除',
        endpoint: '/gateway/merchants/Delete',
        danger: true,
        okText: '商户已删除',
        permission: 'merchant:update',
        showWhen: (r: any) => Number(r.auditStatus) === 10 || Number(r.auditStatus) === 90,
        build: (r: any) => ({ merchantId: r.id }),
        confirm: {
          title: '删除商户',
          message: '只有待审核或已拒绝的商户可删除。有商品或订单的商户不能删除。',
          subject: (r: any) => `${r.merchantName}（${r.merchantNo}）`,
          okText: '删除',
          danger: true,
        },
      },
    ],
    actionsWidth: 210,
  },

  // 商户审核页 = 同一张表，默认落在「待审核」。
  // 不单独写组件：表格、筛选、分页与列表页完全一样，只差一个默认页签。
  merchantAudits: {
    title: '商户审核',
    desc: '审核通过后商户才会出现在小程序里',
    endpoint: '/gateway/merchants/List',
    method: 'POST',
    tabs: [
      { label: '待审核', value: 10 },
      { label: '已通过', value: 20 },
      { label: '已拒绝', value: 30 },
      { label: '全部', value: 0 },
    ],
    byStatus: true,
    defaultStatus: 10,
    statusField: 'auditStatus',
    search: true,
    searchPlaceholder: '商户名 / 编号 / 联系人',
    columns: [
      { field: 'merchantName', label: '商户名', width: 150 },
      { field: 'merchantNo', label: '商户编号', width: 140, format: 'text', mono: true },
      { field: 'platformName', label: '所属平台', width: 130, format: 'text' },
      { field: 'contactName', label: '联系人', width: 110, format: 'text' },
      { field: 'contactPhone', label: '联系电话', width: 130, format: 'text' },
      { field: 'auditStatus', label: '审核', width: 100, dict: 'audit' },
      { field: 'auditRemark', label: '审核意见', width: 200, format: 'text' },
      { field: 'auditorName', label: '审核人', width: 100, format: 'text' },
      { field: 'auditedAt', label: '审核时间', width: 155, format: 'time' },
    ],
    actions: MERCHANT_AUDIT_ACTIONS,
    actionsWidth: 150,
  },

  promotions: {
    title: '营销活动',
    desc: '满减 / 满折 / 满赠，按时间窗生效',
    createRoute: '/promotions/create',
    createLabel: '新建活动',
    createPermission: 'marketing:create',
    rowRoute: (r: any) => `/promotions/edit/${r.activityId ?? r.id}`,
    editRoute: (r: any) => `/promotions/edit/${r.activityId ?? r.id}`,
    editPermission: 'marketing:update',
    endpoint: '/gateway/marketing/activities/List',
    method: 'POST',
    search: true,
    searchPlaceholder: '活动名',
    columns: [
      { field: 'activityName', label: '活动名', width: 180 },
      { field: 'activityType', label: '类型', width: 100, dict: 'promotionType' },
      { field: 'thresholdAmount', label: '门槛', width: 100, num: true, format: 'amount' },
      { field: 'discountValue', label: '优惠', width: 100, num: true, format: 'amount' },
      { field: 'status', label: '状态', width: 90, dict: 'userStatus' },
      { field: 'startTime', label: '开始', width: 155, format: 'time' },
      { field: 'endTime', label: '结束', width: 155, format: 'time' },
    ],
    actions: [
      {
        label: '停用',
        endpoint: '/gateway/marketing/activities/SetStatus',
        danger: true,
        okText: '活动已停用',
        permission: 'marketing:update',
        showWhen: (r: any) => Number(r.status) === 1,
        build: (r: any) => ({ activityId: r.activityId ?? r.id, status: 2 }),
      },
      {
        label: '启用',
        endpoint: '/gateway/marketing/activities/SetStatus',
        okText: '活动已启用',
        permission: 'marketing:update',
        showWhen: (r: any) => Number(r.status) === 2,
        build: (r: any) => ({ activityId: r.activityId ?? r.id, status: 1 }),
      },
      {
        label: '删除',
        endpoint: '/gateway/marketing/activities/Delete',
        danger: true,
        okText: '活动已删除',
        permission: 'marketing:delete',
        build: (r: any) => ({ activityId: r.activityId ?? r.id }),
        confirm: {
          title: '删除营销活动',
          message: '删除后活动不再参与结算；历史订单的优惠金额不会重算。',
          subject: (r: any) => r.activityName,
          okText: '删除',
          danger: true,
        },
      },
    ],
    actionsWidth: 220,
  },

  seckillSessions: {
    title: '秒杀场次',
    desc: '发布时从常规池划出库存',
    createRoute: '/seckill/create',
    createLabel: '新建场次',
    createPermission: 'seckill:create',
    // 点行进「场次商品」而不是编辑：运营从场次列表进来时，
    // 十有八九是要往里加商品，而那才是场次真正要反复做的事。
    rowRoute: (r: any) => `/seckill/items/${r.sessionId ?? r.id}`,
    editRoute: (r: any) => `/seckill/edit/${r.sessionId ?? r.id}`,
    editPermission: 'seckill:update',
    endpoint: '/gateway/marketing/seckill/sessions/List',
    method: 'POST',
    tabs: [
      { label: '全部', value: 0 },
      { label: '未开始', value: 10 },
      { label: '进行中', value: 20 },
      { label: '已结束', value: 30 },
      { label: '已取消', value: 40 },
    ],
    byStatus: true,
    columns: [
      { field: 'sessionName', label: '场次名', width: 190 },
      { field: 'startTime', label: '开始', width: 155, format: 'time' },
      { field: 'endTime', label: '结束', width: 155, format: 'time' },
      { field: 'itemCount', label: '商品数', width: 90, num: true, format: 'count' },
      { field: 'stockTransferred', label: '库存划出', width: 100, dict: 'stockTransferred' },
      { field: 'status', label: '状态', width: 100, dict: 'seckill' },
    ],
    actions: [
      {
        label: '场次商品',
        route: (r: any) => `/seckill/items/${r.sessionId ?? r.id}`,
        permission: 'seckill:update',
      },
      {
        label: '发布',
        endpoint: '/gateway/marketing/seckill/sessions/Publish',
        okText: '场次已发布',
        permission: 'seckill:update',
        showWhen: (r: any) => Number(r.status) === 10,
        build: (r: any) => ({ sessionId: r.sessionId ?? r.id }),
        confirm: {
          title: '发布秒杀场次',
          message: '发布时会从常规库存中划出本场商品需要的库存。发布后不能继续添加商品。',
          subject: (r: any) => r.sessionName,
          okText: '发布场次',
        },
      },
      {
        label: '结束',
        endpoint: '/gateway/marketing/seckill/sessions/Finish',
        danger: true,
        okText: '场次已结束',
        permission: 'seckill:end',
        showWhen: (r: any) => Number(r.status) === 20,
        build: (r: any) => ({ sessionId: r.sessionId ?? r.id }),
        confirm: {
          title: '结束秒杀场次',
          message: '结束后立即回补未售出的秒杀库存，场次不可再恢复。',
          subject: (r: any) => r.sessionName,
          okText: '结束',
          danger: true,
        },
      },
    ],
    actionsWidth: 260,
  },

  refunds: {
    title: '退款列表',
    desc: '审批通过才真正退钱',
    endpoint: '/gateway/refunds/List',
    method: 'POST',
    tabs: [
      { label: '全部', value: 0 },
      { label: '待审批', value: 10 },
      { label: '已退款', value: 20 },
      { label: '已拒绝', value: 90 },
    ],
    byStatus: true,
    search: true,
    searchPlaceholder: '退款单号 / 订单号',
    columns: [
      { field: 'refundNo', label: '退款单号', width: 150, format: 'text', mono: true },
      { field: 'orderNo', label: '订单号', width: 190, format: 'text', mono: true },
      { field: 'refundType', label: '类型', width: 110, dict: 'refundType' },
      { field: 'amount', label: '退款金额', width: 110, num: true, format: 'amount' },
      { field: 'reason', label: '申请原因', width: 200, format: 'text' },
      { field: 'approverName', label: '审批人', width: 100, format: 'text' },
      { field: 'status', label: '状态', width: 100, dict: 'refund' },
      { field: 'createdAt', label: '申请时间', width: 155, format: 'time' },
    ],
    // 退款详情是独立页面而不是弹窗：明细行（退到哪个商品、退了多少）
    // 才是部分退款争议的全部，弹窗里放不下也读不完。
    rowRoute: (r: any) => `/refunds/detail/${r.refundId ?? r.id}`,
    actions: [
      {
        label: '通过',
        endpoint: '/gateway/refunds/Approve',
        okText: '已通过',
        permission: 'refund:approve',
        danger: false,
        build: (r: any) => ({ refundId: r.refundId }),
        // 只在待审批的行上出现：已审批的单再点一下只会拿到
        // 「该退款单已处理」这类报错，给一个必然失败的按钮没有意义。
        showWhen: (r: any) => r.status === 10,
        confirm: {
          title: '通过退款',
          message: '通过后钱会真的退给客户，且不可撤销。',
          subject: (r: any) => `${r.refundNo}（${r.orderNo}）`,
          okText: '确认退款',
        },
      },
      {
        label: '拒绝',
        endpoint: '/gateway/refunds/Reject',
        danger: true,
        okText: '已拒绝',
        permission: 'refund:reject',
        build: (r: any, reason: string) => ({ refundId: r.refundId, rejectReason: reason }),
        showWhen: (r: any) => r.status === 10,
        confirm: {
          title: '拒绝退款',
          message: '客户会看到拒绝原因，请写清楚。',
          subject: (r: any) => `${r.refundNo}（${r.orderNo}）`,
          okText: '拒绝',
          danger: true,
          withReason: true,
          reasonLabel: '拒绝原因',
          reasonPlaceholder: '客户要知道为什么被拒，否则只能反复申请',
        },
      },
    ],
    actionsWidth: 130,
  },

  // 支付单。后台此前完全没有入口（只有 C 端的 payments/Query 按订单号查单条），
  // 运营想看「今天有哪些单支付失败」都做不到。
  payments: {
    title: '支付列表',
    desc: '模拟支付通道的单据，按状态与单号筛选',
    endpoint: '/gateway/admin/payments/List',
    method: 'POST',
    tabs: [
      { label: '全部', value: 0 },
      { label: '待支付', value: 1 },
      { label: '已支付', value: 20 },
      { label: '已关闭', value: 30 },
    ],
    byStatus: true,
    search: true,
    searchPlaceholder: '支付单号 / 订单号',
    columns: [
      { field: 'paymentNo', label: '支付单号', width: 210, format: 'text', mono: true },
      { field: 'orderNo', label: '订单号', width: 200, format: 'text', mono: true },
      { field: 'amount', label: '支付金额', width: 110, num: true, format: 'amount' },
      // 必须标 dict：不标就会渲染成裸的 1 —— 界面上出现枚举数字违反 UI-RAW-003，
      // 而运营会把它当成「渠道 Id」。文案取后端下发的 channelName。
      { field: 'channel', label: '渠道', width: 100, dict: 'paymentChannel' },
      { field: 'status', label: '状态', width: 100, dict: 'payment' },
      { field: 'failReason', label: '失败原因', width: 180, format: 'text' },
      { field: 'paidAt', label: '支付时间', width: 155, format: 'time' },
      { field: 'createdAt', label: '创建时间', width: 155, format: 'time' },
    ],
  },

  // 积分流水。跨客户查询，所以和 C 端的「我的积分流水」不是一个接口。
  pointRecords: {
    title: '积分流水',
    desc: '全站积分变动明细，含变动前后余额',
    endpoint: '/gateway/points/RecordsAll',
    method: 'POST',
    search: true,
    searchPlaceholder: '业务单号',
    columns: [
      { field: 'customerId', label: '客户 Id', width: 170, format: 'text', mono: true },
      { field: 'bizNo', label: '业务单号', width: 200, format: 'text', mono: true },
      { field: 'action', label: '动作', width: 90, dict: 'pointAction' },
      { field: 'quantity', label: '变动', width: 100, num: true, format: 'count' },
      { field: 'beforeAvailable', label: '变动前可用', width: 110, num: true, format: 'count' },
      { field: 'afterAvailable', label: '变动后可用', width: 110, num: true, format: 'count' },
      { field: 'lotExpireAt', label: '批次到期', width: 155, format: 'time' },
      { field: 'remark', label: '备注', width: 180, format: 'text' },
      { field: 'createdAt', label: '发生时间', width: 155, format: 'time' },
    ],
  },

  couponTemplates: {
    title: '券模板',
    desc: '改模板不影响已发出的券，已发出的券按自己的快照算',
    createRoute: '/coupons/templates/create',
    createLabel: '新建券模板',
    createPermission: 'coupon-template:create',
    rowRoute: (r: any) => `/coupons/templates/edit/${r.templateId ?? r.id}`,
    editRoute: (r: any) => `/coupons/templates/edit/${r.templateId ?? r.id}`,
    editPermission: 'coupon-template:update',
    endpoint: '/gateway/marketing/coupon-templates/List',
    method: 'POST',
    tabs: [
      { label: '全部', value: 0 },
      { label: '启用', value: 1 },
      { label: '停用', value: 2 },
    ],
    byStatus: true,
    search: true,
    searchPlaceholder: '模板名',
    columns: [
      { field: 'templateName', label: '模板名', width: 180 },
      { field: 'couponType', label: '类型', width: 100, dict: 'couponType' },
      { field: 'thresholdAmount', label: '门槛', width: 100, num: true, format: 'amount' },
      { field: 'discountAmount', label: '优惠额', width: 100, num: true, format: 'amount' },
      { field: 'discountRate', label: '折扣率', width: 100, num: true },
      { field: 'validDays', label: '有效期', width: 100, num: true, format: 'count' },
      { field: 'issuedQuantity', label: '已发放', width: 100, num: true, format: 'count' },
      { field: 'totalQuantity', label: '发行量', width: 100, num: true, format: 'count' },
      { field: 'status', label: '状态', width: 100, dict: 'enable' },
    ],
    actions: [
      {
        label: '停用',
        endpoint: '/gateway/marketing/coupon-templates/Update',
        danger: true,
        okText: '券模板已停用',
        permission: 'coupon-template:update',
        showWhen: (r: any) => Number(r.status) === 1,
        build: (r: any) => ({
          templateId: r.templateId ?? r.id,
          templateName: r.templateName,
          couponType: r.couponType,
          thresholdAmount: r.thresholdAmount,
          discountAmount: r.discountAmount,
          discountRate: r.discountRate,
          giftTemplateId: r.giftTemplateId,
          validDays: r.validDays,
          totalQuantity: r.totalQuantity,
          perUserLimit: r.perUserLimit,
          perOrderLimit: r.perOrderLimit,
          sortOrder: r.sortOrder,
          status: 2,
        }),
        confirm: {
          title: '停用券模板',
          message: '停用后不能再被领取，已经发出的券不受影响。',
          subject: (r: any) => r.templateName,
          okText: '停用',
          danger: true,
        },
      },
      {
        label: '启用',
        endpoint: '/gateway/marketing/coupon-templates/Update',
        okText: '券模板已启用',
        permission: 'coupon-template:update',
        showWhen: (r: any) => Number(r.status) === 2,
        build: (r: any) => ({
          templateId: r.templateId ?? r.id,
          templateName: r.templateName,
          couponType: r.couponType,
          thresholdAmount: r.thresholdAmount,
          discountAmount: r.discountAmount,
          discountRate: r.discountRate,
          giftTemplateId: r.giftTemplateId,
          validDays: r.validDays,
          totalQuantity: r.totalQuantity,
          perUserLimit: r.perUserLimit,
          perOrderLimit: r.perOrderLimit,
          sortOrder: r.sortOrder,
          status: 1,
        }),
      },
      {
        label: '删除',
        endpoint: '/gateway/marketing/coupon-templates/Delete',
        danger: true,
        okText: '券模板已删除',
        permission: 'coupon-template:delete',
        showWhen: (r: any) => Number(r.issuedQuantity || 0) === 0,
        build: (r: any) => ({ templateId: r.templateId ?? r.id }),
        confirm: {
          title: '删除券模板',
          message: '只有尚未发放过的模板可以删除。已发放过请改为停用。',
          subject: (r: any) => r.templateName,
          okText: '删除',
          danger: true,
        },
      },
    ],
    actionsWidth: 220,
  },

  couponActivities: {
    title: '券活动',
    desc: '领券中心。发放量与模板发行池子是两个独立池子',
    createRoute: '/coupons/activities/create',
    createLabel: '新建券活动',
    createPermission: 'coupon-activity:create',
    rowRoute: (r: any) => `/coupons/activities/edit/${r.activityId ?? r.id}`,
    editRoute: (r: any) => `/coupons/activities/edit/${r.activityId ?? r.id}`,
    editPermission: 'coupon-activity:update',
    endpoint: '/gateway/marketing/coupon-activities/List',
    method: 'POST',
    tabs: [
      { label: '全部', value: 0 },
      { label: '启用', value: 1 },
      { label: '停用', value: 2 },
    ],
    byStatus: true,
    search: true,
    searchPlaceholder: '活动名',
    columns: [
      { field: 'activityName', label: '活动名', width: 180 },
      { field: 'templateName', label: '券模板', width: 180, format: 'text' },
      { field: 'claimStartTime', label: '领取开始', width: 155, format: 'time' },
      { field: 'claimEndTime', label: '领取结束', width: 155, format: 'time' },
      { field: 'claimQuantity', label: '发放量', width: 100, num: true, format: 'count' },
      { field: 'claimedQuantity', label: '已领取', width: 100, num: true, format: 'count' },
      { field: 'targetType', label: '适用范围', width: 110, dict: 'targetType' },
      { field: 'status', label: '状态', width: 100, dict: 'enable' },
    ],
    actions: [
      {
        label: '停用',
        endpoint: '/gateway/marketing/coupon-activities/Update',
        danger: true,
        okText: '券活动已停用',
        permission: 'coupon-activity:update',
        showWhen: (r: any) => Number(r.status) === 1,
        build: (r: any) => ({
          activityId: r.activityId ?? r.id,
          activityName: r.activityName,
          templateId: r.templateId,
          claimStartTime: r.claimStartTime,
          claimEndTime: r.claimEndTime,
          claimQuantity: r.claimQuantity,
          perUserLimit: r.perUserLimit,
          targetType: r.targetType,
          targets: '[]',
          sortOrder: r.sortOrder,
          status: 2,
        }),
        confirm: {
          title: '停用券活动',
          message: '停用后客户无法再领取；已经领取的券不受影响。',
          subject: (r: any) => r.activityName,
          okText: '停用',
          danger: true,
        },
      },
      {
        label: '启用',
        endpoint: '/gateway/marketing/coupon-activities/Update',
        okText: '券活动已启用',
        permission: 'coupon-activity:update',
        showWhen: (r: any) => Number(r.status) === 2,
        build: (r: any) => ({
          activityId: r.activityId ?? r.id,
          activityName: r.activityName,
          templateId: r.templateId,
          claimStartTime: r.claimStartTime,
          claimEndTime: r.claimEndTime,
          claimQuantity: r.claimQuantity,
          perUserLimit: r.perUserLimit,
          targetType: r.targetType,
          targets: '[]',
          sortOrder: r.sortOrder,
          status: 1,
        }),
      },
    ],
    actionsWidth: 210,
  },

  files: {
    title: '文件管理',
    desc: '已上传的文件。移除只清列表，不删存储中的内容',
    endpoint: '/gateway/files/List',
    method: 'POST',
    search: true,
    searchPlaceholder: '原始文件名',
    columns: [
      { field: 'originalName', label: '文件名', width: 220, format: 'text' },
      { field: 'category', label: '分类', width: 100, dict: 'file' },
      { field: 'extension', label: '扩展名', width: 100, format: 'text', mono: true },
      { field: 'sizeText', label: '大小', width: 100, num: true },
      { field: 'provider', label: '存储', width: 90, format: 'text' },
      { field: 'createdAt', label: '上传时间', width: 155, format: 'time' },
    ],
    actions: [
      {
        label: '移除',
        endpoint: '/gateway/files/Delete',
        danger: true,
        permission: 'file:upload',
        build: (r: any) => ({ fileId: r.fileId }),
        okText: '已移除',
        confirm: {
          title: '移除文件',
          message: '从文件库移除这条记录。存储中的文件不会被删除。',
          subject: (r: any) => r.originalName,
          okText: '移除',
        },
      },
    ],
    actionsWidth: 120,
  },

  logisticsCompanies: {
    title: '物流公司',
    desc: '发货表单的下拉数据源，内置常用快递公司',
    createRoute: '/orders/logistics-companies/create',
    createLabel: '新建物流公司',
    rowRoute: (r: any) => `/orders/logistics-companies/edit/${r.logisticsId ?? r.id}`,
    editRoute: (r: any) => `/orders/logistics-companies/edit/${r.logisticsId ?? r.id}`,
    actions: [
      {
        label: '删除',
        endpoint: '/gateway/logistics-companies/Delete',
        danger: true,
        okText: '已删除',
        permission: 'logistics:manage',
        build: (r: any) => ({ logisticsId: r.logisticsId ?? r.id }),
        confirm: {
          title: '删除物流公司',
          message: '只是从字典里移除；已发货的单存的是公司名快照，不受影响。',
          subject: (r: any) => r.companyName,
          okText: '删除',
        },
      },
    ],
    actionsWidth: 150,
    endpoint: '/gateway/logistics-companies/List',
    method: 'POST',
    tabs: [
      { label: '全部', value: 0 },
      { label: '启用', value: 1 },
      { label: '停用', value: 2 },
    ],
    byStatus: true,
    search: true,
    searchPlaceholder: '公司名 / 编码',
    columns: [
      { field: 'companyName', label: '公司名称', width: 180 },
      { field: 'companyCode', label: '编码', width: 110, format: 'text', mono: true },
      { field: 'sortOrder', label: '排序', width: 90, num: true, format: 'count' },
      { field: 'status', label: '状态', width: 100, dict: 'enable' },
      { field: 'updatedAt', label: '更新时间', width: 155, format: 'time' },
    ],
  },
};

export default LISTS;
